### ISSUE TITLE
Leave from party doesn't work

### ISSUE THREAD

**Issue by Fireworrks** [Exslims/MercuryTrade#169]
When I'm invited to a party for a trade once complete I select Leave from Party however 100% of the time I get the message in chat "The target of this operation was not a party member."

**Comment by IronMask75** [comment]
[edit] The reason (I've since found) is that you need to set up your nickname in Settings -> Notification Panel -> Your nickname(for leave option).
Put your character name in the text field (not sure if using your PoE account name here works).

I found this by finding a duplicate topic in the Closed issues. Perhaps there needs to be a way to make this more clear. Pin the issue instead of closing it? Change the first-start tutorial to alert people to the feature and how to set it up?

**Comment by remcoros** [comment]
I can confirm. Always get the "The target of this operation was not a party member." message.

**Comment by Exslims** [comment]
specify your nickname in settings guys

**Comment by remcoros** [comment]
Oops, I've set it to a different chars name. TY!
