### ISSUE TITLE
Not working after reinstallation.

### ISSUE THREAD

**Issue by ghost** [Exslims/MercuryTrade#235]
Hello! First and foremost, great application! Love it, otherwise i wouldn't bother to write a ticket here.

So I recently decided to reinstall Path of Exile on a different drive on my computer. After this process I've also reinstalled mercury trade. (I have followed the instructions, deleted the history file and completely resetted mercury trade. I have tried to use the .jar download and also the .rar download) But i just can't get it to work. The overlay is there, but i'm not receiving any notification from the chat scanner nor the incoming/outgoing messages.
I'm not entirely sure what I'm doing wrong. I've made sure the installation is handled properly and that all the folders are found by the application(tried both manually and automatically).

Thank you in advance!

**Comment by Saiasanc** [comment]
First go into the settings under General and just double check that the Path of Exile folder is correct. Then go under Notification panel and ensure you have your character name typed correctly in the "Your nickname" field.  And lastly just to be sure, check that under Incoming notifications the Enabled box is checked. ;)

**Comment by ghost** [comment]
Did all that yesterday in the extensive testing, but for good measure i did a clean install again.
1. Deleted the Mercury Trade + The history folder
2. Re-Downloaded both the .jar and the .rar
3. Put them both in my PoE folder in 'My Games', same as .filter files for example.
4. Ran the .jar
5. Checked all the points you mentioned and it was all correct
6. Did not work.
7. I then tried extracting the .rar and ran the .exe as admin and then followed the previous steps but with same result
8. I finally tried it with the .jar found in the .rar, same result.

Still no notifications =/ super weird. I assume it's me doing something wrong but i really cant figure out what it is. I did a clean re-installation between each attempt. Mercury trade locates the folder automatically and it is the correct one.

**Comment by Sklifan** [comment]
some idea's (hope something of this helps)
- were there any updates?
 -> windows/operating system, java, network general?
- check the registry (regedit) for mercury-trade and old links for POE
- try to run exe as admin (or not as admin)
- check the security - settings for java

**Comment by ghost** [comment]
Thank you for your time, I tried the above but without any success, the result is the same. Admittedly I didn't quite know what to look for in regedit and I 'think' everything is normal in java settings. 

This is all very infuriating since i had it working for a week or two prior to the reinstall.

I don't wanna go back to trading like a peasant..

**Comment by Aledark789** [comment]
I have the same issue and i've tryed everything like Kevinrapey.

My problem is it constantly try to load since the new update. I've tried to run it for an hour.

**Comment by pendo324** [comment]
Same issue as @Aledark789 here. Downloaded and ran the new release and it just stays loading indefinitely.

**Comment by ghost** [comment]
I just want to clarify I have not been experiencing indefinite loading. The software is up and running, the overlay is there but it is not reacting to any messages (in-, outgoing or such tagged by the chatscanner)

**Comment by Sklifan** [comment]
Hey,
Please check the wiki as well:
https://github.com/Exslims/MercuryTrade/wiki/Troubleshooting
-> this might help:
"Problem: Notifications don't pop-up when receiving a trade messages.

Fix: Please make sure you've selected the correct Path of Exile folder.

if you delete MercuryTrade folder from %userprofile%/appdata/local, run poe client + run mercury, game path will be found automatically"

When you have completely deleted Mercury Trade (with history folder) and installed it new, were there again the question about the path of POE and the tutorial showed up again?
If not, maybe you are starting still the old/installed version of Mercury Trade, that is using the old configuration.

**Comment by ghost** [comment]
Yeah I have checked that as well. I have tried both methods. locating the path manually and letting the software find the location automatically.
Yeah when i re-install i get the folder-question and also the tutorial. This is something I've done between every "test" to make sure I get a fresh reset every time.

**Comment by Sklifan** [comment]
Hey,
Have you tried this as well?
"Problem: Buttons don't work (if you use poe trade macro)
Fix: Uncheck "Put tooltip results on clipboard" in the iteminfo tab in poe trade macro."

so the installation doesn't seems to be wrong, it should be something else that doesn't allow the notifications :)

As well check the "https://github.com/Exslims/MercuryTrade/wiki/Advanced-troubleshooting"

and post the log here or any error messages, maybe this will help to understand the problem better.

**Comment by ghost** [comment]
Is this what you needed? It looks exactly the same as in the picture.
Did a clean install again, currently running the .jar (from the .rar download if that makes any difference)
checked that all the settings are good and that the folders/nickname is correct as well as the chat scanner being active, started and running the correct terms.

I've checked my trademacro and the option you mention is unchecked and has been since i first experienced issues with mercury trade. During this test I decided to not even start the trademacro or even AHK(so no other macros running)

Thank you for taking the time, and just say the word if you want me to test something differently or again as i haven't been super thorough this time around.

C:\Users\Elias>java -jar C:\Users\Elias\Desktop\MercuryTrade\MercuryTrade.jar

JNativeHook: Global keyboard and mouse hooking for Java.
Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
https://github.com/kwhat/jnativehook/

JNativeHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

JNativeHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by Sklifan** [comment]
Hey,

that's only the beginning of the log-file (as far as I can see this).
Try to let it run while you are using the tool.
There is a similar behavior regarding the notifications in https://github.com/Exslims/MercuryTrade/issues/220
As well, since this worked before and the new installation is not working, maybe there is some components the tool required, that are not installed like java/ run-time. Unfortunately I don't know what the program exactly needs to run without problem, I think it's java only.
Is it possible to switch to old setup where it was still running without problem?
And were there any other changes beside the new installing of Path of Exile - any hardware changes, PC restarts (that maybe activated some updates that were standing out for longer time).
That are just some ideas and I hope some of them would help you or maybe getting you to further ideas/solutions.
Btw. have you tried older versions of the program? Maybe this would work(better), so you could trade as long as this one is not solved.
And one more thing -> check this:
"Leaving this comment here as my problem had a different solution but googling my problem lead here. Sometimes after downloading the file in windows 10 it will have a checked option that disables it from reading and editing certain files in the system, this prevented it from detecting notifications on my computer. Unchecking it fixed the issue"
https://github.com/Exslims/MercuryTrade/issues/139
So check if the logfile/whole folder of Mercury/POE folder is writable.
And one more thing:
"Download and install Java on your computer, then open MercuryTrade.jar. Because the program operates on top of a Path of Exile window as an overlay, make sure your client is not in fullscreen mode."
Do you run POE in windowed mode since the new installation?

**Comment by ghost** [comment]
Ok so this is the weirdest.. It's suddenly working!

I launched it just as ive done a billion times now(deleted the history folder first as always).
ran the program through cmd. so i could provide you with a log. and im suddenly getting the notifications again. 

Since i don't know much about these things i tried to run it again without cmd and its still working.

There is one difference from last time. Like I said, i don't know anything about these kind of things so I don't know if this has any effect? But I had troubles launching PoE this morning due to a failed update through Steam, so i had to clear the download cache and repair the steam library folder and re-download the patch to get the game running again. Could this be something?

Just to clarify I didn't have time to test your suggestions in the previous post as it very unexpectedly started working.

So I think for now I'll just let it be as it is, and if I encounter any further issues ill update the thread. If theres any more info you want from me just say the word, im very grateful for the time you put into this!

Thank you!

**Comment by Sklifan** [comment]
Hey,
Glad to hear it's working. 
The update / reinstall of poe actually could be the solution, since as you've said there were no other changes beside this and the behavior started after new installation the first time, maybe this was the problem. As long as this is working, let it run - never touch the running system xD

Happy trading!
