### ISSUE TITLE
[Feature request] Support for multiple screens

### ISSUE THREAD

**Issue by tbarusseau** [Exslims/MercuryTrade#307]
Right now, using MercuryTrade with several screens is a bit strange. I went from single-screen to multiple screens with the same MercuryTrade installed, and some weird issues happened:

- The "lock"/"move panels" window will always appear on the first (i.e. main) screen. There doesn't seem to be a way to tell MercuryTrade that I want it on the other screen. Even using the <win-shift-[left|right]> shortcut doesn't seem to move the sotware from one screen to another.

- The grid placeholder never appear anymore, and I can't even configure it through the "lock"/"move panels" option.

- The windows sometimes disappear, even if the sound is still working. Restarting the software seems to temporarily fix this issue.

**Comment by jessebevil** [comment]
I use it with multiple monitors. The game requires focus for the notifications to appear. This is due to the way it's coded and I've located the spot in the code myself, though I've been unable to find a toggle. Removing that as a feature isn't ideal, but rather creating a tickbox or something to enable/disable it as a feature would be great. 

I've had no issues with the grid placeholder appearing, clicking the toolbar grid image pops up the grid for me to adjust, however it tries to "snap" in places which prevent me from lining it up exactly. You don't configure the grid with the relocate windows option, you do it with the grid box option. 

I've also had no issue moving the notifications off screen, and then hitting lock. While I can't move the "Panels Unlocked" window, I don't have a need for it as it goes away once locked.
